Models/ErrorViewModel.cs
namespace Registro_de_Fornecedores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FornecedorModel.cs
using System.ComponentModel.DataAnnotations;

namespace Registro_de_Fornecedores.Models
{
    public class FornecedorModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o Nome do Fornecedor")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Digite o CNPJ do Fornecedor")]
        public int CNPJ { get; set; }
        
        public string Especialidade { get; set; }
    }
}

Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using Registro_de_Fornecedores.Models;
using Registro_de_Fornecedores.Repositorio;

namespace Registro_de_Fornecedores.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorRepositorio _fornecedorRepositorio;
        public FornecedorController(IFornecedorRepositorio fornecedorRepositorio)
        {
            _fornecedorRepositorio = fornecedorRepositorio;
        }
        public IActionResult Index()
        {
            List<FornecedorModel> fornecedor = _fornecedorRepositorio.BuscarTodos();
            return View(fornecedor);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            FornecedorModel fornecedor = _fornecedorRepositorio.ListarPorId(id);
            return View(fornecedor);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            FornecedorModel fornecedor = _fornecedorRepositorio.ListarPorId(id);
            return View(fornecedor);
        }

        public IActionResult Apagar(int id)
        {
            bool apagado = _fornecedorRepositorio.Apagar(id);
            try
            {
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Fornecedor apagado com sucesso";

                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu fornecedor";

                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu fornecedor,mais detalhes:{erro.Message}";
                return RedirectToAction("Index");
            }
        }
    

    [HttpPost]
    public IActionResult Criar(FornecedorModel fornecedor)
    {
         try
           {
             if (ModelState.IsValid)
               {
                   _fornecedorRepositorio.Adicionar(fornecedor);
                   TempData["MensagemSucesso"] = "Fornecedor cadastrado com sucesso";
                    return RedirectToAction("Index");
                }
                    return View(fornecedor);
            }
            catch (System.Exception erro)
            {
                _fornecedorRepositorio.Adicionar(fornecedor);
                TempData["MensagemErro"] = $"Ops,não conseguimos adicionar o cadastrado, mais informações :{erro.Message}";
                     return RedirectToAction("Index");
            }
    }

    [HttpPost]
    public IActionResult Alterar(FornecedorModel fornecedor)
    {
            try
            {
                if (ModelState.IsValid)
                {
                    _fornecedorRepositorio.Atualizar(fornecedor);
                    TempData["MensagemSucesso"] = "fornecedor atualizado com sucesso";
                    return RedirectToAction("Index");
                }
                     return View("Editar", fornecedor);
            }
             catch(System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops,não conseguimos atualizar o cadastrado, mais informações :{erro.Message}";
                return RedirectToAction("Index");
            }
    }
}
}
    

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Registro_de_Fornecedores.Models;
using System.Diagnostics;

namespace Registro_de_Fornecedores.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Fornecedor/ApagarConfirmacao.cshtml
@model FornecedorModel
@{
    ViewData["Title"] = "Confirma apagar Fornecedor";
}

<div class="text-center">
    <h3>Realmente deseja apagar o Fornecedor (@Model.Name) ?</h3>
</div>
<a class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Index">Cancelar</a>
<a class="btn btn-danger" role="button" asp-controller="Fornecedor" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar</a>

Views/Fornecedor/ApagarConfirmaçao.cshtml
@{
    ViewData["Title"] = "Confirma apagar Fornecedor";
}

<div class="text-center">
    <h3>Realmente deseja apagar o Fornecedor ?</h3>
</div>
<a class="btn btn-primary" role="button">Cancelar</a>
<a class="btn btn-danger">Confirmar</a>

Views/Fornecedor/Criar.cshtml
@model FornecedorModel
@{
    ViewData["Title"] = "Criar de Fornecedores";
}


<form style="border: 1px solid black; border-radius: 10px;" class="justify-content-center align-items-center" asp-controller="Fornecedor" asp-action="Criar" method="post">
   <div style="width: 600px;" class="container m-10">
        <div class="text-center">
            <h3>
                <small class="text-muted">Cadastro de fornecedor</small>
            </h3>
        </div>
     <div class="row mb-4 align-items-center">
            <div class="col-1 pe-0"><i class="bi bi-person-circle"></i></div>
            <div class="col-11 ps-0">
                <input type="text" asp-for="Name" class="form-control input-default" placeholder="Nome do fornecedor">
                @Html.ValidationMessageFor(x => x.Name)
            </div>
     </div>

        <div class="row mb-4 align-items-center">
            <div class="col-1 pe-0">
                <i class="bi bi-file-text"></i>
            </div>
            <div class="col-11 ps-0">
            <input type="text" asp-for="CNPJ" class="form-control input-default" placeholder="CNPJ do fornecedor">
         @Html.ValidationMessageFor(x => x.CNPJ)
         </div>
     </div>
        <div class="row mb-4 align-items-center">
            <div class="col-1 pe-0">
            <i class="bi bi-building"></i>
            </div>
            <div class="col-11 ps-0">
                <select type="text" asp-for="Especialidade" class="form-control input-default">
                    <option value="">Escolha a Especialidade</option>
                    <option value="Comércio">Comércio</option>
                    <option value="Serviço">Serviço</option>
                    <option value="Indústria">Indústria</option>
                </select>
            </div>
   
         @Html.ValidationMessageFor(x => x.Especialidade)
      </div>
      <div class="row mb-4">
        <div class="col-2"><button type="submit" class="btn btn-primary">Adicionar</button></div>
         <div class="col-10">
            <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index">Voltar</a>
         </div>
      </div>
      </div>
</form>

Views/Fornecedor/Editar.cshtml
@model FornecedorModel
@{
    ViewData["Title"] = "Editar Listagem de Fornecedores";
}

<div class="text-center">

    <h1 class="display-4">cadastrar Fornecedor</h1>

</div>

<form asp-controller="Fornecedor" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="digite o nome do fornecedor">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        <label for="nome">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" placeholder="digite o CPJ do fornecedor">
        @Html.ValidationMessageFor(x => x.CNPJ)
    </div>
    <div class="form-group">
        <label for="Especialidade">Especialidadelabel </label>
        <select type="text" asp-for="Especialidade" class="form-control" placeholder="digite o Especialidade do fornecedor">
            <option value="">Escolha a Especialidader</option>
            <option value="Comércio">Comércio</option>
            <option value="Serviço">Serviço</option>
            <option value="Indústria">Indústria</option>
        </select>
        @Html.ValidationMessageFor(x => x.Especialidade)
    </div>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
    <br/>
</form>

Views/Fornecedor/Index.cshtml
@model List<FornecedorModel>
@{
    ViewData["Title"] = "Listagem de Fornecedores";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<div class="text-center">
    <br />
    <h1 display-4>Listagem de Fornecedores</h1>
     <table class="table">
          <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">CNPJ </th>
                <th scope="col">Especialidade </th>
                <th scope="col"> </th>
            </tr>
        </thead>
         <tbody>
            @if (Model != null && Model.Any())
            {
                foreach(FornecedorModel fornecedor in Model)
                {
                    <tr>
                        <th scope="row">@fornecedor.Id</th>
                        <td>@fornecedor.Name</td>
                        <td>@fornecedor.CNPJ</td>
                        <td>@fornecedor.Especialidade</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@fornecedor.Id" asp-controller="Fornecedor" asp-action="Editar"><i class="bi bi-trash3-fill"></i></a>
                                <a role="button" class="btn btn-danger" asp-route-id="@fornecedor.Id" asp-controller="Fornecedor" asp-action="ApagarConfirmacao"><i class="bi bi-pencil-fill"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table> 
  </div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

         <div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de Fornecedores</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Cadastro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Registro_de_Fornecedores.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav style="background-color: #607C8A;" class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Registro de Fornecedores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fornecedor" asp-action="Criar"><i class="bi bi-person-circle me-2"></i><span>Cadastro</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fornecedor" asp-action="Index"> <i class="bi bi-list-ul me-2"></i><span>Fornecedores</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container align-items-center">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

            <footer class="text-center text-white fixed-bottom" style="background-color: #607C8A;">
                <!-- Grid container -->
                <div class="container p-4 pb-0">
                    <!-- Section: CTA -->
                    <section class="">
                        <p class="d-flex justify-content-center align-items-center">
                    <span class="me-2">&copy; 2023 - Desenvolvido por</span>
                            <a href="https://github.com/wesleybert" class="text-white" target="_blank">
                                Wesley Berto
                            </a>
                        </p>
                    </section>
                    <!-- Section: CTA -->
                </div>
            </footer>
            <!-- Footer -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>